### ISSUE TITLE
Nejde se připojit na Discord

### ISSUE THREAD

**Issue by Eugleo** [adamnemecek/adjoint#2]
Ahoj, link na Discord z nějakého důvodu nefunguje, neposlal bys nový? Díky!

**Comment by adamnemecek** [comment]
Toto nefunguje? https://discord.gg/mr9TAhpyBW

**Comment by adamnemecek** [comment]
Ses v 100 discord channels?

**Comment by Eugleo** [comment]
Update: link z Twitteru funguje 🤔
